### ISSUE TITLE
Amazing

### ISSUE THREAD

**Issue by iongion** [divshot/firebase-rpc#1]
This is an amazing job, but why is the library so large - 172.666 kb
I've looked inside it and it appears you are either implementing Promises or concatenating a promises library, if that is the case, could you prevent it from happening ?
Are there any caveats ?
What happen with calls that are invoked on remote clients but those clients disconnect ?
How does this work ? Do you use a queue ?
A while ago I've posted a question on StackOverflow:
http://stackoverflow.com/questions/24937568/emulate-rpc-with-firebase
And I am using those recommendations there but I have hard time finding out what to do with RPC messages that get into the queue but both the invoker and invoked clients disconnect. The queue gets polluted and dirty. It still works but I do not like current implementation because I have to create a clean-up facility.

edit: BTW - would you submit this to npm also ?

**Comment by mbleigh** [comment]
The bulk of the file weight is just in the extensive comments on the Q promises library. You'll notice that the minified version is a very reasonable 19k, so I don't think it's really a problem.

This is still very early code so I'm not quite ready to ship it to NPM and Bower officially just yet. Thanks for the praise though!

At present, the library doesn't do any kind of sweeping or cleanup -- it just marks jobs as "complete." This is obviously not going to scale so it should be considered a todo for the library.
